name: FAST
channels:
    - conda-forge
dependencies:
    - python>=3.5
    - xrootd
    - pip
    - pip:
      - pyyaml 
      - uproot 
      - fast_curator 
      - fast_carpenter
      - fast_plotter